# Generated by Django 3.1.2 on 2020-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtitle',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
