# Generated by Django 3.1.2 on 2020-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201027_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='thumbtail',
            field=models.URLField(blank=True, max_length=20000),
        ),
    ]
